# Generated by Django 4.1 on 2024-11-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideritem',
            options={'ordering': ('order',), 'verbose_name': 'Элемент слайдера', 'verbose_name_plural': 'Элементы слайдера'},
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
